name: my-first-workflow
on: workflow_dispatch
jobs: 
  first_job:
    runs-on: ubuntu-latest    
    steps:
      - name: Print greeting
        run: echo "Hello World!"
      - name: Print goodbye
        run: echo "Done - bye!"
      - name: multi-line step
        run: |
          echo " Line 1";
          echo " Line 2"
